name: Pull Request Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  core:
    name: Build
    uses: ./.github/workflows/common.yml
    with:
      type: PullRequest